local opt = vim.opt
opt.backup = false                          -- creates a backup file
opt.clipboard = "unnamedplus"               -- allows neovim to access the system clipboard
opt.cmdheight = 1                           -- more space in the neovim command line for displaying messages
opt.completeopt = { "menuone", "noselect" } -- mostly just for cmp
opt.conceallevel = 0                        -- so that `` is visible in markdown files
opt.fileencoding = "utf-8"                  -- the encoding written to a file
opt.hlsearch = true                         -- highlight all matches on previous search pattern
opt.ignorecase = true                       -- ignore case in search patterns
opt.mouse = "a"                             -- allow the mouse to be used in neovim
opt.pumheight = 10                          -- pop up menu height
opt.showmode = false						-- show the neovim mode (disable when using a statusline)
opt.showtabline = 1                         -- always show tabs
opt.smartcase = true                        -- smart case
opt.smartindent = true                      -- make indenting smarter again
opt.splitbelow = true                       -- force all horizontal splits to go below current window
opt.splitright = true                       -- force all vertical splits to go to the right of current window
opt.swapfile = false                        -- creates a swapfile
opt.termguicolors = true                    -- set term gui colors (most terminals support this)
opt.timeoutlen = 1000                       -- time to wait for a mapped sequence to complete (in milliseconds)
opt.undofile = true                         -- enable persistent undo
opt.updatetime = 300                        -- faster completion (4000ms default)
opt.writebackup = false                     -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
opt.shiftwidth = 4                          -- the number of spaces inserted for each indentation
opt.tabstop = 4                             -- insert 4 spaces for a tab
opt.cursorline = true                       -- highlight the current line
opt.number = true
opt.relativenumber = true                   -- set relative numbered lines
opt.numberwidth = 5                         -- set number column width {default 4}
opt.signcolumn = "yes"                      -- always show the sign column, otherwise it would shift the text each time
opt.foldmethod = "indent"                   -- fold text based on the indentation
opt.foldlevel = 99                          -- every fold is open when opening a file
opt.wrap = false                            -- display lines as one long line
opt.shortmess:append 'c'					-- Discrete messages
vim.cmd "set whichwrap+=<,>,[,],h,l"			-- Improve the way you move (more intuitive) 
vim.g.loaded_netrw = 1							-- disable netrw
vim.g.loaded_netrwPlugin = 1					-- disable netrw, use a tree-explorer plugin instead
